# Generated by Django 2.1 on 2020-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('votes', models.CharField(default='0', max_length=20)),
                ('videofile', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
    ]
